### ISSUE TITLE
Build Errors

### ISSUE THREAD

**Issue by BoBiene** [notzippy/repo-tool#2]
`# repo-tool
.\repo-tool.go:756:14: ref.IsBranch undefined (type *plumbing.Reference has no field or method IsBranch)
.\repo-tool.go:756:30: ref.IsRemote undefined (type *plumbing.Reference has no field or method IsRemote)
.\repo-tool.go:756:46: ref.IsTag undefined (type *plumbing.Reference has no field or method IsTag)
.\repo-tool.go:951:15: undefined: pty.Start`

Seems like it is the line #756:
`println(ref.IsBranch(), ref.IsRemote(), ref.IsTag(), ref.String(), "->", ref.Target().String())`

and #951:
`if f, err := pty.Start(res); err != nil {`

Any suggestions?

**Comment by notzippy** [comment]
That function on line #756 was a new one that I was trying out and it appears the dependent library signature had changed.
Line #951 should work - did you fetch the latest package `go get -u github.com/kr/pty` ?
Thanks for pointing this out, I need to get back to this :-D

**Comment by BoBiene** [comment]
Thank you. Looks like the pty package is not available for Windows.
Is there a chance to get it to work on Windows?

**Comment by notzippy** [comment]
Possibly, I think the only issue in Windows is finding the git executable.
I can test that this weekend...

**Comment by BoBiene** [comment]
Great 👍
